### ISSUE TITLE
Error on selecting region when creating a new project

### ISSUE THREAD

**Issue by eahefnawy** [jaws-framework/JAWS#109]
To reproduce, just create a new project, follow the steps till you get to the select region step, once you select a region, you should get this error.

This seems to be too basic to be the first one to notice it, so I'm guessing it might be specific to my env. I'm running on OSX Yosemite.

anybody else facing this issue?
```
Eslams-MacBook-Pro:prod eslam$ jaws new project
       ____   _____  __      __  _________ 
      |    | /  _  \/  \    /  \/   _____/ 
      |    |/  /_\  \   \/\/   /\_____  \  
  /\__|    /    |    \        / /        \ 
  \________\____|__  /\__/\__/ /_________/ v1 (BETA)

       *** The Server-Less Framework ***     

JAWS: Enter a project name:  (jaws-Nk6KNdyC) test
JAWS: Enter a stage for this project:  (dev) dev
JAWS: Enter an AWS S3 Bucket name to store this project's env vars:  (jaws.yourapp.com) jaws.test
JAWS: Enter an email to use for AWS alarms:  (you@yourapp.com) xxx@gmail.com
JAWS: Enter the ACCESS KEY ID for your Admin AWS IAM User:  xxx 
JAWS: Enter the SECRET ACCESS KEY for your Admin AWS IAM User:  xxx
JAWS: Select a region for your project: 
    1) us-east-1
  > 2) us-west-1
    3) eu-west-1
    4) ap-northeast-1
/usr/local/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/promise.js:677
            throw e;
                  ^
Error: ENOENT, no such file or directory '/Users/eslam/.aws/credentials'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.readFileSync (/usr/local/lib/node_modules/jaws-framework/node_modules/aws-sdk/lib/util.js:102:35)
    at Object.module.exports.profilesMap (/usr/local/lib/node_modules/jaws-framework/lib/utils/aws.js:66:38)
    at /usr/local/lib/node_modules/jaws-framework/lib/commands/new_project.js:231:37
    at tryCatcher (/usr/local/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (/usr/local/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/usr/local/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
Eslams-MacBook-Pro:prod eslam$ 
```

**Comment by boushley** [comment]
This is actually because you've finished the new process, unrelated to region selection.

I believe if you create a `.aws` directory in your home directory it should solve this problem.

Looks like when we or the AWS library go to create the credential file that if `~/.aws` doesn't exist things fail.

**Comment by eahefnawy** [comment]
yep that solves it! thanks a lot @boushley! I created the credentials file as stated [here](https://github.com/jaws-framework/JAWS/blob/master/docs/admin-env.md). It's mentioned in the docs, I guess I missed it :)

However, since it asked me for my access key and secret when the file didn't exist, shouldn't it create the file for me? I imagine someone new to AWS could struggle a bit with this error.

**Comment by boushley** [comment]
Glad you got it working. It definitely is a bug. It would have created the file for you if the folder had existed. We need to extend the tool to create the folder first.

Interested in opening a pull request fixing the problem?

**Comment by doapp-ryanp** [comment]
Good catch. I'll fix this in the `cf-deploy` branch that we are using to do the huge refactor for v1.

**Comment by doapp-ryanp** [comment]
Closing. Fixed in https://github.com/jaws-framework/JAWS/commit/488ec8db6cb34526b5a2441f04ec5e4eb3ed3b19#diff-d20b04e7995c472fd8d658bd13b486feR80

**Comment by doapp-ryanp** [comment]
hmm that totally pasted like poop. https://github.com/jaws-framework/JAWS/commit/488ec8db6cb34526b5a2441f04ec5e4eb3ed3b19#diff-d20b04e7995c472fd8d658bd13b486feR77

**Comment by doapp-ryanp** [comment]
Sorry for the spam. my direct line linking in the commit diff is not working. its in there, just search for `/aws.js`

**Comment by eahefnawy** [comment]
ha! perrrfect! thanks!
