### ISSUE TITLE
[v1] CredentialsError: Missing credentials in config

### ISSUE THREAD

**Issue by nil1511** [jaws-framework/JAWS#120]
On setting ~/.aws/credentials as shown in the wiki
```
[default]
AWS_ADMIN_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
AWS_ADMIN_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
```
JAWS is not able to create new project 
```{ [CredentialsError: Missing credentials in config]
  cause:
   { [CredentialsError: Missing credentials in config]
     message: 'Missing credentials in config',
     code: 'CredentialsError',
     time: Tue Sep 15 2015 12:22:49 GMT+0530 (IST),
     originalError:
      { message: 'Could not load credentials from SharedIniFileCredentials',
        code: 'CredentialsError',
        time: Tue Sep 15 2015 12:22:49 GMT+0530 (IST),
        originalError: [Object] } },
  isOperational: true,
  code: 'CredentialsError',
  time: Tue Sep 15 2015 12:22:49 GMT+0530 (IST),
  originalError:
   { message: 'Could not load credentials from SharedIniFileCredentials',
     code: 'CredentialsError',
     time: Tue Sep 15 2015 12:22:49 GMT+0530 (IST),
     originalError: { message: 'Credentials not set in /Users/Nil/.aws/credentials using profile default' } } }```

and it is working as 
```
[default]
aws_access_key_id = AKIAIOSFODNN7EXAMPLE
aws_secret_access_key = wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
```

Please check and update accordingly.
Thanks for creating this framework

**Comment by dekz** [comment]
Wiki has been updated: 

https://github.com/jaws-framework/JAWS/wiki/v1:-AWS-Account-setup/686c35d40d00741cfc4db8dea23f034b1121c713

**Comment by flashsnake-so** [comment]
I am also seeing this issue even my credentials are setup correctly.

**Comment by eahefnawy** [comment]
@flashsnake-so thanks for reporting. Could you please open a new issue with your specific case and environment info? This issue is VERY outdated and even the Error messages might have changed. And don't forget to mention your Serverless version.

Cheers!!

**Comment by flashsnake-so** [comment]
@eahefnawy Thanks for your response. It turns out that it is my environment setting issue.  Don't worry about it.  This module rocks~~!!

**Comment by eahefnawy** [comment]
@flashsnake-so you're awesome! thanks for letting us know 😊
