### ISSUE TITLE
Requires shelljs installed globally before jaws cli works

### ISSUE THREAD

**Issue by binoculars** [jaws-framework/JAWS#127]
Probably should be in the README or not require a separate global install (don't know if this is possible, just something to be aware of).

Before:
<img width="563" alt="screen shot 2015-09-19 at 00 34 20" src="https://cloud.githubusercontent.com/assets/3374510/9974613/54b1330c-5e66-11e5-8130-ec9b6bcc2a73.png">

After:
<img width="567" alt="screen shot 2015-09-19 at 00 36 31" src="https://cloud.githubusercontent.com/assets/3374510/9974622/87ede792-5e66-11e5-8366-9db170baab38.png">

**Comment by markogresak** [comment]
The problem is probably that [shelljs is a devDependency](https://github.com/jaws-framework/JAWS/blob/master/package.json#L36) and therefore isn't installed with `npm install`.
