### ISSUE TITLE
Creating CloudFormation Stack for your new project fails

### ISSUE THREAD

**Issue by goliatone** [jaws-framework/JAWS#149]
Happy to provide any further information you might need

```
JAWS: Select a profile for your project: 
  > default
JAWS: \ Creating CloudFormation Stack for your new project (~5 mins)...{ [LimitExceededException: Limit for stacks has been exceeded]
  cause: 
   { [LimitExceededException: Limit for stacks has been exceeded]
     message: 'Limit for stacks has been exceeded',
     code: 'LimitExceededException',
     time: Wed Sep 23 2015 16:38:08 GMT-0400 (EDT),
     statusCode: 400,
     retryable: false,
     retryDelay: 30 },
  isOperational: true,
  code: 'LimitExceededException',
  time: Wed Sep 23 2015 16:38:08 GMT-0400 (EDT),
  statusCode: 400,
  retryable: false,
  retryDelay: 30 }
```

**Comment by doapp-ryanp** [comment]
the error says 'Limit for stacks has been exceeded'.  You have hit your AWS acct limit for # of CF stacks. u need to request an increase.

**Comment by goliatone** [comment]
apologize, obviously did not properly read the error... not that I'm that familiar with CF anyhow. Thanks

**Comment by ksac1** [comment]
HI. I am getting an error : resource limit exceeded. (Service: AWSLogs; Status Code: 400; Error Code: LimitExceededException; Request ID: 

What is the solution for such errors?

**Comment by gamecraftCZ** [comment]
Hi @ksac1 ,
I use [serverless-plugin-split-stacks](https://www.npmjs.com/package/serverless-plugin-split-stacks) plugin for serverless, that splits it the deploy in multiple CF stacks to prevent the limit.
1. `npm install serverless-plugin-split-stacks`
2. Add it to serverless.yml plugins:
```
plugins:
    - serverless-plugin-split-stacks
```
3. Add config for it (docs are in README of the plugin)  

It should like something like this:
```
custom:
    splitStacks:
        perFunction: true
        perType: false
        perGroupFunction: false
        stackConcurrency: 10
        resourceConcurrency: 10
```

**Comment by sac-s** [comment]
Split stacks would not solve the issue, as mentioned earlier either raise a support ticket to AWS asking to increase the stack limit, or remove unwanted CF stacks deployed in your account
