### ISSUE TITLE
Add non-interactive mode that disables spinners

### ISSUE THREAD

**Issue by boushley** [jaws-framework/JAWS#158]
I currently run some deployments for this from my CI server. The spinner adds quite a few lines to the logs.

It would be nice to skip the spinner if jaws is being run in a non-interactive manner (we can detect this via `process.stdout.isTTY`). We may also want to add a flag to force non-interactive mode. Is this something you're open to me implementing?

I'm thinking of creating a method in `utils/cli.js` that we use to determine if we are interactive or not. This can be used throughout the code base to change the way things are handled. I would then update `utils/cli.js#spinner` to return a mock spinner object that doesn't do anything if we're in a non-interactive context.

Another addition might be returning an error when a command is run in non-interactive mode without all options specified, instead of prompting for the values in a non-interactive context.

**Comment by doapp-ryanp** [comment]
closing. fixed in PR above

**Comment by boushley** [comment]
Awesome! Thanks @shortjared
