### ISSUE TITLE
Changing Project S3 Bucket Organization (while keeping the functionality)

### ISSUE THREAD

**Issue by ac360** [jaws-framework/JAWS#160]
I did a talk on JAWS on Thursday night and noticed people were confused why the S3 buckets for keeping your JAWS project env vars, lambda backups, and cloudformation templates were created once per project region, and not created for each region AND stage your project uses.  They were right, this is confusing, since it breaks our theme of perfect replication of project AWS resources for each stage/region your project uses. 

I propose creating a separate JAWS project bucket for each stage/region your project uses and adding this "project" bucket to the `resources-cf.json`.  In `jaws.json`, we will remove the `jawsBuckets` property and instead put your project S3 bucket for that stage/region in the `stages` property, within each respective stage/region, alongside the IAM roles.  You can update these values at any time to re-use S3 buckets for multiple jaws projects.

The documentation diagrams have already been updated and you can see how everything will look [here](https://github.com/jaws-framework/JAWS/blob/master/docs/deployment.md#jaws-deployment). It's clean.  It's easy to understand.

**Comment by boushley** [comment]
Are we going to make people pick a bucket name for each of these? Or are we going to assume they give us a unique bucket prefix / suffix, and then we'll be appending the stage / region to the name for them?

Since bucket names must be globally unique people can get a bit picky about bucket names. There is also a limit of 100 buckets per account. I'm guessing most people won't run into this, but it's something to keep in mind.

**Comment by ac360** [comment]
@boushley Here is how I'm currently implementing it.   Let me know if you have suggestions...

* User creates a new project and is now prompted to enter a domain.
* Domain is persisted to their jaws.json
* All buckets are then created in this format region.stage.domain (us-east-1.prod.myapp.com).  Hopefully, this will ensure uniqueness, as long as their domain is unique.
* A new `jawsBucket` property is added to each stage/region json object (jawsBucket: us-east-1.prod.myapp.com)
* The bucket key structure looks like `JAWS/proejct/stage/region/data (data = envVars, cloudformation, lambdas) so you can still go through each stage/region in your jaws.json and enter in the same bucket.  If you only want to use one, instead of a new bucket for each stage/region.

I think they raised the bucket limit to 300.

**Comment by boushley** [comment]
Docs still say 100: http://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_s3 although that may be out of date...

I might add something like `jaws-` to the front of the buckets if you're going to use their domain name as the base. So something like `jaws.us-east-1.prod.myapp.com`

Other than that, this looks great!

**Comment by ac360** [comment]
Great idea!  I'm adding in a 'jaws' prefix.

**Comment by prestomation** [comment]
The bucket limit is still 100. Just last month AWS started raising this limit upon request, this was previously a hard-limit: https://aws.amazon.com/about-aws/whats-new/2015/08/amazon-s3-introduces-new-usability-enhancements/

**Comment by ac360** [comment]
Fixed in v1.3
