### ISSUE TITLE
Question: Lambda function names format

### ISSUE THREAD

**Issue by jodagm** [jaws-framework/JAWS#162]
I am trying to figure out how lambda names are constructed, specifically the trailing part that adds 13 random alphanumeric chars. 

The reason its important to me is because some of my lambdas are invoked by SWF decider:

```
 swf.respondDecisionTaskCompleted({
    taskToken: decisionTask.taskToken,
    decisions: [{
      decisionType: 'ScheduleLambdaFunction',
      scheduleLambdaFunctionDecisionAttributes: {
        id: 'dev-myProject-l-lmyLambdaName-1L7K2VUAN72MB',
        name: 'dev-myProject-l-lmyLambdaName-1L7K2VUAN72MB',
        input: decisionTask.events[0].workflowExecutionStartedEventAttributes.input
      }
    }]
  }
``` 

obviously I can only hard code this: '1L7K2VUAN72MB'  just for testing.
Is there a best practice as to how should I refer to a lambda name is such a scenario?

Thanks,
Jonathan

**Comment by ac360** [comment]
@jodagm Hmm, I'm not sure how to fix this.  

Lambda names are generated via the generateLambdaName function in utils/index.js.  

However, the random string is an ID that CloudFormation adds to the end of the Lambda.  JAWS has no control over that.  Its purpose, I believe, is to help CloudFormation identify Lambdas that belong to certain stacks.

Programmatically, you could call CloudFormation describeStacks() via the AWS-SDK to fetch all Lambdas in a stack.  It will return all of their Lambda function names.

**Comment by jodagm** [comment]
Thanks @ac360 , that's a good idea. I'll dig into that.

**Comment by ac360** [comment]
Good luck! :)
