### ISSUE TITLE
JAWS v0.0.3 causes breaking changes.  Here's how to fix them.

### ISSUE THREAD

**Issue by ac360** [jaws-framework/JAWS#23]
In v0.0.3, I had to make some breaking changes and I apologize for this.  JAWS literally went from 9 - 2000 github stars in 24 hours.  I thought I would have some more time to make some changes before people cared about it.  Either way, I still have to make the changes, and they are a bit ugly for people using v0.0.1.  

**Here is how you can upgrade from v0.0.1 to v0.0.3:**

* Download JAWS v0.0.3
* In the `cli` module, run `npm install`, then run `npm install ./ -g` to install the new JAWS CLI globally.
* In the `lib` module, run `npm install`.  You will have to re-npm-link it to your Lambda functions since the name in the `lib` module was changed from `app-lib` to 'jaws-lib'.  So, in `lib` run `npm link`.
* In each of your Lambda functions run `npm link jaws-lib`.
* Lastly, there was an issue with the users/signin function creating a new user record in the DynamoDB database on each sign-in.  This issue was due to a mistake in setting up the DynamoDB.  
* You need to delete the existing Users DynamoDB table and recreate it.  When you create the new table, name it `jaws_users`, and set the *Primary Key Type* as *Hash*.  Make sure the *Hash Attribute Name* is set to *string* and name it `_id`.

Again, I apologize for this.  This is the last big breaking change for a while.  Soon, I will bring JAWS out of pre-release and use proper semantic versioning. 

Let me know if you haves issues.  I'm here to help you :)  

Lots of awesome stuff is coming soon to JAWS and soon we will all be building massively scalable web apps that do not require managing servers!

**Comment by ac360** [comment]
The [Installation Guide](https://github.com/servant-app/JAWS/wiki/JAWS-Installation) has also been updated appropriately.

**Comment by austinrivas** [comment]
Thanks for documenting the upgrade path, worked like a charm. Clean install was also fine.

**Comment by ac360** [comment]
@austinrivas thanks for the feedback :)  So much cool stuff coming.  Stay tuned!

**Comment by JerrySievert** [comment]
running `jaws run`, i'm getting the following error:

```
sys is deprecated. Use util instead.
****** JAWS: Running Lambda Function Locally...
****** JAWS: Lambda Returned An Error:
{ status: 401, message: 'Invalid or expired access token' }
```

i copied the role ARN from the `jaws_lambda_role`, and set it in .env, `AWSLambdaFullAccess` is set in the role.

any ideas?

**Comment by JerrySievert** [comment]
as an aside, i tried creating a new access key, same issue.

thanks!
