### ISSUE TITLE
Error connect ETIMEDOUT following quickstart guide

### ISSUE THREAD

**Issue by behboud** [jaws-framework/JAWS#259]
just following the quickstart guide I get the following error after jaws dash:
```
{ [Error: connect ETIMEDOUT 54.239.38.6:443]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '54.239.38.6',
  port: 443 }
```
what am I doing wrong?

**Comment by eahefnawy** [comment]
You mean after you hit `Deploy Selected`? or right after `jaws dash`?

**Comment by nicornk** [comment]
After I press Deploy Selected:
JAWS: -------------------------------------------  
JAWS:  Dashboard:  Deploying Endpoints...  
JAWS: -------------------------------------------  
JAWS: Endpoint Deployer:  Deploying endpoint(s) to region "eu-west-1"...  
JAWS: Endpoint Deployer:  "dev - eu-west-1": found 1 endpoints to deploy  

{ [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }

**Comment by sixlettervariables** [comment]
If you open `https://lambda.eu-west-1.amazonaws.com/` in a browser, do you see something like:

```xml
<MissingAuthenticationTokenException>
  <Message>Missing Authentication Token</Message>
</MissingAuthenticationTokenException>
```

**Comment by behboud** [comment]
setting region to us-east-1 works...

**Comment by behboud** [comment]
must have been issue on AWS side. Works on all regions now. closing issue

**Comment by brainframe-me** [comment]
Still having this problem in eu-west-1, simply followed the basic greetings hello steps.
Any ideas?

**Comment by maludwig** [comment]
Hey, for future users, this was an issue on the AWS side for me. I tried to work on a project on Feb 28, 2017, when AWS was experiencing an outage, check the AWS Service Health Dashboard here:

https://status.aws.amazon.com/

**Comment by pmuens** [comment]
Thanks for the update @maludwig 👍
