### ISSUE TITLE
Remove deployment status from awsm.json

### ISSUE THREAD

**Issue by marklawlor** [jaws-framework/JAWS#280]
Working as a team, our git history is starting to get polluted updates like this

```
--- a/aws_modules/api/<endpoint>/awsm.json
+++ b/aws_modules/api/<endpoint>/awsm.json
@@ -1,7 +1,7 @@
 {
   "lambda": {
     "envVars": [],
-    "deploy": false,
+    "deploy": true,
     "package": {
       "optimize": {
         "builder": "browserify",
```

I also believe we had this scenario occur within our team:

1. Developer1 performs `git pull`, unknowingly pulling down AWSM module A with deploy set to true
2. Developer2 makes changes to module "A" and deploys them.
3. Developer1 makes changes to module "B" and deploys it with `jaws deploy`
4. Developer1 has now unknowingly overwritten developer2's work in module "A"

I think the deploy options should be move out of the AWSM file and into a seperate hidden '.jaws/.deploy.json'

**Comment by doapp-ryanp** [comment]
Yep its gone in our next release that is coming out soon. Closing
