### ISSUE TITLE
Justify the "(cheap) apps!" claim with real numbers

### ISSUE THREAD

**Issue by mikeatlas** [jaws-framework/JAWS#282]
Without sample usage levels and established sets of canonical apps built along these lines, "cheap" is not really justifiably claimable for a lot of reasons:
 
- learning curve cost per team/individual
- debug, tracing, logging, profiling and optimization challenges cost (time ~= money)
- lack of comparison of execution speed
- lack of cost basis of comparison (aside from the digression in SES/Lambda #140) side-by-side

I think your real challenge is that a JAWS "application" could range from massively low cost set of simple tasks that run occasionally to massively high-cost, high volume workloads that just don't make sense to be built in such a manner.

Personally, I would suggest you go with the term "neat" instead of "cheap" because I can think of many real-world use cases that would be *neat* and *easy* to build with a JAWS-style architecture, yet still cost lots of dollars to run real-world large workloads to achieve already-solved solutions at scale.

**Comment by ac360** [comment]
:+1: We're going to add all of this information in the new documentation (almost done).  We definitely need to be much more informative and helpful here.  Thanks for filing this issue, Mike :)
