### ISSUE TITLE
`jaws dash` has rendering problems with long lists

### ISSUE THREAD

**Issue by Nopik** [jaws-framework/JAWS#284]
When the list of lambdas + endpoints is higher than the height of terminal window, the menu displayed by `jaws dash` starts to have issues.

**Comment by doapp-ryanp** [comment]
Dash is completely gone in the upcoming v1.4 release.  Much easier unix style `<path> ...` format for lambda deploy.

Dash as we know it will be replaced by a super cool web interface after next release.

**Comment by Whoaa512** [comment]
Any news on this? It's rather annoying to have to decrease my terminal font size just so I can deploy multiple functions.

**Comment by pmuens** [comment]
@Whoaa512 thanks for bringing that up again.

We're currently working on v1 where the whole UX will be improved. We'll consider this feedback as it's important for large Serverless applications. You might take a sneak peek here: 
https://github.com/serverless/serverless/tree/v1.0
