### ISSUE TITLE
Stages management

### ISSUE THREAD

**Issue by katspaugh** [jaws-framework/JAWS#294]
I created a project and 3 stages using this command:

```
jaws stage create
```

And then deployed each of the new stages using `jaws dash`.

JAWS created 3 Lambda functions for me and 3 API Gateway resources (each with one stage). What I expected was that JAWS would re-use a single Lambda function and a single API Gateway resource with 3 stages like on this screenshot:

<img width="230" alt="screen shot 2015-11-09 at 17 30 30" src="https://cloud.githubusercontent.com/assets/381895/11039545/7a864048-8708-11e5-964c-ec13fe177cf6.png">

What's the reasoning behind the decision to make JAWS work like this?

**Comment by dcrockwell** [comment]
The bigger question to me is why you would want to re-use a single lambda function. Wouldn't that make it impossible to have different versions for each stage?

**Comment by yyolk** [comment]
There is versioning in Lambda but currently theres no way to tie a stage or stage(s) from api-gateway to a version or alias.

**Comment by katspaugh** [comment]
@dcrockwell both [Lambda](http://docs.aws.amazon.com/lambda/latest/dg/versioning-aliases.html) and [API Gateway](http://docs.aws.amazon.com/apigateway/latest/developerguide/stages.html) (and JAWS is already making use of stages in API Gateway–in it's own way).

@yyolk sounds reasonable. I would still like to hear what authors/contributors would say. Maybe I've configured something wrong?

**Comment by shortjared** [comment]
The lambda versioning was released fairly recently, which just happened to coincide with a heroic level core rewrite by @ac360 and @doapp-ryanp for a plugin oriented architecture. The JAWS framework is going to leverage API gateway stages and better lambda versioning support soon.

[Check out the roadmap for more info on these issues and more](https://docs.google.com/document/d/1SeTgtsQc620vcwgGMZ4F2yuWVf-A3JmpTn1VT8pKYsA/edit#heading=h.x5xoxm80prla)

From the RoadMap...

## Incorporate New Lambda Versioning & Aliases
AWS Lambda now features versioning and aliasing support.  We need to implement a new deployment workflow to incorporate these new features.
...
This flow will allow multiple developers to work on the same lambda in their own stage while preventing collisions.  Also provides a clear and methodical release planning with quick and easy roll-back support


## Fix API Gateway Deployment To Use Stages Accurately (GitHub Issue #192)

When deploying API Gateway endpoints, JAWS creates a separate REST API on APIG for each stage.  JAWS should use a single REST API per region and create multiple stages within that.

**Comment by katspaugh** [comment]
@shortjared thank you very much for the detailed and patient reply! I was honestly searching in existing issues but hadn't found #192 before.

Glad to know it's on the roadmap! Cheers!
