### ISSUE TITLE
Will JAWS support scheduled lambdas?

### ISSUE THREAD

**Issue by yaochen** [jaws-framework/JAWS#297]
when creating the modules, maybe allow user to choose either api gateway endpoint and/or an event source?

use case:

flag base processing, scheduled lambda continues to run via its schedule(cron), api gateway allows user to quickly curl(probably with api key) to turn on/off the lambda or features of that lambda(ie set send email to false).

**Comment by doapp-ryanp** [comment]
Support for sched. lambda is already in the currently  being worked on next release..

**Comment by shortjared** [comment]
We all want this just as bad as you!

However, the ONLY way to create scheduled event sources as of right now is via the console.

[From the scheduled events docs:](http://docs.aws.amazon.com/lambda/latest/dg/getting-started-scheduled-events.html)

>This functionality is only available when you create a Lambda function using the AWS Lambda console. The console provides the Scheduled Event as an event source. At the time of creating a Lambda function, you choose this event source and specify a time interval.
**Note**
Each AWS account can have up to 50 unique event sources of the Scheduled Event source type. Each of these can be the event source for up to five Lambda functions. That is, you can have up to 250 Lambda functions that can be executing on a schedule in your AWS account.

I have made do with create a lambda function via JAWS, then using the console to attach a scheduled event source. **The scheduled event source will persist through future deploys.** However, if you deploy to a new stage or region, you'll need to attach the scheduled event source.

**Comment by yaochen** [comment]
thanks for the info, @doapp-ryanp @shortjared !

looking fwd to the schedule lambda support!

**Comment by aletheia** [comment]
I think we could gain the same effect using what stated here

http://www.slideshare.net/mobile/AmazonWebServices/cmp407-lambda-as-cron-scheduling-invocations-in-aws-lambda

Couldn't we?

Il giorno gio 12 nov 2015 alle 21:17 Yao Chen <notifications@github.com> ha
scritto:

**Comment by shortjared** [comment]
@aletheia You certainly can! I built something extremely similar internally at my company that we use a a lot. (Along with a CloudFormation that kickstarts the entire minute CloudFormation -> SNS ticker.)

The complexity lies in the fact that now you have to know the names of the other lambda functions which are dynamically named by CloudFormation if you are using JAWS (somewhat solved recently by aliases, not supported by JAWS yet. v1.4 solves this though) or bundle everything in the same big lambda. Then you have to write / maintain the cron config and hope your "god" lambda function doesn't miss or get broken for some reason (Although we have had a minutely lambda trigger once a minute for the past 3 months straight... so this probably is not a huge concern in my book.)

Scheduled event sources are far more elegant and unless you need reliable minute resolution or are using many stages / regions, I think it's quite much easier to setup via console until scheduled event source drops via CloudFormation / SDK.

I was considering building an awsm-cron until scheduled events dropped... maybe I should consider it again.
