### ISSUE TITLE
module install removed in master?

### ISSUE THREAD

**Issue by sielay** [jaws-framework/JAWS#309]
Got something like that

```
jaws module install https://github.com/jaws-framework/jaws-core-js 
Unsupported cmd install. Must be install|update|create
```

Looks like function support was removed from `/bin/jaws`. Which branch supports it and is stable to use? Tried `v1.4` but it crashes too

**Comment by sielay** [comment]
This one removed functionality https://github.com/jaws-framework/JAWS/commit/c6b75f542fa6ae6167af1ab11e22a82e8478fb7b#diff-332cd46c06179c62a8050405a3a0e209

**Comment by sielay** [comment]
As I see your further commits it looks like docs need bit updating.

**Comment by sielay** [comment]
Ok likely I found solution on github of users awsm. Should we now use `jaws postinstall awsm-users npm`? If so, please update docs ;) I am closing it until I wouldn't find new precise bug.

**Comment by eahefnawy** [comment]
@sielay really sorry for your bad experience. We're very busy finishing v1.4, and after that we'll make sure we have solid docs :)
