### ISSUE TITLE
Your Input Is Needed For JAWS V1

### ISSUE THREAD

**Issue by ac360** [jaws-framework/JAWS#56]
We've listened to everyone's requests and I sincerely think we've implemented all of them!

Please take a second to review the specifications for JAWS v1 in the Google Document located below.

You can comment on the document.  Bigger spec issues should be posted as a new issue and prefixed with SPEC V1: in the Issue title.

I hope you all like this.  We're working hard to deliver the greatest server-less framework ever (powered by AWS, of course).

Cheers,
Austen

**[The JAWS V1 Specifications Document](https://docs.google.com/document/d/1SeTgtsQc620vcwgGMZ4F2yuWVf-A3JmpTn1VT8pKYsA/edit?usp=sharing)**

**Comment by kvnlnt** [comment]
Make it SAWS and dont look back. :D

**Comment by ashack293** [comment]
Nice work! 
One thing I noticed is, in the **Code Style** section, the link to idiomatic is broken.

Should we be able to see comments in the doc?

**Comment by ac360** [comment]
Everyone can now comment on the google document.

**Comment by ac360** [comment]
@ashack293 Fixed.  And everyone can now comment directly on the Google Document.  You might need to refresh.
