### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by flatiron32** [jaws-framework/JAWS#66]
This looks awesome and I want it to work yesterday. I don't have a time machine so i will settle for it working tomorrow. How can I help?

I see a few issues marked as "help wanted" and I see a top of great stuff in the roadmap doc. How do i find the highest value thing that needs to get done?

**Comment by ashack293** [comment]
+1

**Comment by ac360** [comment]
I'm working with @doapp-ryanp on JAWS V1.  We're moving fast and rapidly refactoring stuff.  Soon it will be more stable and easier for others to PR.  

In the interim, please look at the `jaws-modules` section.  We're looking to create a module/template ecosystem of pre-written back-end functions/tasks, that every JAWS user can easily mix and install into their project with the `jaws install ` command. 

A single lambda function can be a module, or a group of lambda functions can be a module.  Here are some ideas: 

* lambda-img-resizer-java, 
* lambda-sms-sender-twilio-js,
* lambda-email-sender-ses-java,
* lambdas-user-crud-dynamodb-cognito-js, 
* lambdas-user-crud-mysql-jwt-java, 
* lambdas-essential-event-handlers,
* lambdas-third-party-authenticators,

Being able to mix and match pre-built back-end modules, written in various programming languages, and ready to be deployed in their own containers (lambdas) is a **beautiful** thing!!!  If you'd like to help, writing some useful modules would be awesome!

The jaws-module `jaws.json` specifications are changing a lot, so keep watching that.  But, the functions you write won't change at all.

**Comment by ollierattue** [comment]
"lambda-img-resizer-java" - could you provide details on how you would see this one functioning.

**Comment by tobyhede** [comment]
@ac360 Is the v1 branch where we should be looking/working?

**Comment by ac360** [comment]
@tobyhede Yes :)

**Comment by ac360** [comment]
We now have [aws-modules (awsm)](https://github.com/awsm-org/awsm) and JAWS V1.  Everything is looking fantastic.  Check out aws-modules if you are looking for an easy way to help.  There is huge opportunity here.
